# Site configuration
# Add social networks

markdown: kramdown
highlighter: rouge
permalink: /:title/
url: https://lukalafaye.github.io/Jekyll-MarkDown
encoding: UTF-8
sass:
    sass_dir: _sass

title: Title
description: Description of this blog

#########################################
#  Add # sign to enable                 #
#########################################

codepen: User
facebook: User
github: User
instagram: User
twitter: User
youtube: User
